name: CI/CD to Google Cloud Run
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set GCP Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/bible-rag-app:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: bible-rag-app
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/bible-rag-app:latest
          region: ${{ secrets.GCP_REGION }}
          env_vars: GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
